apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasources
  namespace: monitoring
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki.monitoring.svc.cluster.local:3100"
      isDefault: false
      jsonData:
        maxLines: 1000
