apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: $NAMESPACE
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:$loki_version
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-data
              mountPath: /data
            - name: loki-config
              mountPath: /config/loki.yaml
              subPath: loki.yaml
          args:
            - -config.file=/config/loki.yaml
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
      volumeMounts:
        - name: loki-data
          mountPath: /data
      volumes:
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc